info:
  title: APIFlask
  version: 0.1.0
tags:
- name: Match
servers:
- url: http://localhost:5000/
paths:
  /match/text:
    get:
      parameters:
      - in: query
        name: query_text
        schema:
          type: string
        required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
          description: Successful response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation error
      tags:
      - Match
      summary: Match Text
  /match/{course_code}:
    get:
      parameters:
      - in: path
        name: course_code
        schema:
          type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
          description: Successful response
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Not found
      tags:
      - Match
      summary: Match Code
openapi: 3.0.3
components:
  schemas:
    ValidationError:
      properties:
        detail:
          type: object
          properties:
            <location>:
              type: object
              properties:
                <field_name>:
                  type: array
                  items:
                    type: string
        message:
          type: string
      type: object
    HTTPError:
      properties:
        detail:
          type: object
        message:
          type: string
      type: object
    Course:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
        language:
          type: string
        desc:
          type: string
        period:
          type: string
        sisu_link:
          type: string
        mycourses_link:
          type: string
        credits:
          type: integer
